### ISSUE TITLE
MInecraft 1.21 Not available, please update Metadata server (?)

### ISSUE THREAD

**Issue by lemonzest79** [unmojang/FjordLauncher#10]
### Operating System

Linux

### Version of Fjord Launcher

Fjord Launcher 8.3.2

### Version of Qt

Qt 6.2.4

### Description of bug

Went to Install Minecraft 1.21 and it is missing from the list of available versions

### Steps to reproduce

Attempt to create an instance or change a current instances Minecraft version and 1.21 is not listed

### Suspected cause

Maybe the Metadata server is not currently updated with version 1.21?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by evan-goode** [comment]
Resolved, thanks. In the future we could look into redirecting most requests to Prism's metadata server since the only thing github.com/unmojang/meta does differently is authlib-injector.
