### ISSUE TITLE
The Add Microsoft account button in Accounts menu is disabled

### ISSUE THREAD

**Issue by GoodGameInfinity** [unmojang/FjordLauncher#11]
### Operating System

Linux

### Version of Fjord Launcher

Fjord Launcher 8.3
Platform: flatpak

### Version of Qt

Qt 6.7.1

### Description of bug

The button "Add Microsoft" in the Settings > Accounts menu is greyed out
![image](https://github.com/unmojang/FjordLauncher/assets/81247214/79918410-4053-4658-a91f-0b71f40526e5)

### Steps to reproduce

Open the Settings > Accounts menu

### Suspected cause

The logic for adding a Microsoft account wasn't implemented or the button hasn't been re-enabled since the fork from PollyMC.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GoodGameInfinity** [comment]
Just read the release readme and understood that my issue is not a bug, so sorry about that, yet it would very awesome if somebody could add a default API key. Anyway I'll close the issue as not planned because it's not a bug.

**Comment by evan-goode** [comment]
Fixed in 8.4
