### ISSUE TITLE
New upstream release

### ISSUE THREAD

**Issue by lemonzest79** [unmojang/FjordLauncher#12]
### Role

I play modded minecraft

### Suggestion

Squawk

### Benefit

So the codebase is current

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.4

The usual upstream release update, thanks

**Comment by evan-goode** [comment]
Merged PrismLauncher 8.4 to our develop branch, would you mind testing it? Builds will be here: https://github.com/unmojang/FjordLauncher/actions/runs/9634646584. I may work on putting a client ID in Fjord and release Fjord 8.4 when that's done.

**Comment by lemonzest79** [comment]
Seems to be working ok with both Microsoft Accounts and Ely.by authlib-injector accounts, tested joining my own personal servers, Better Than Adventure Latest Pre-Release (MS Account) and Enigmatica 9 (Ely.by/authlib-injector account) both worked as normal
![2024-06-23_18 53 19](https://github.com/unmojang/FjordLauncher/assets/40669977/747b81a1-6ee5-404c-bf54-02dbc0ea007b)

Ely.by can be seen in the F3 output

**Comment by lemonzest79** [comment]
Getting `QNetworkReply::ContentAccessDenied` with the key 8.4 pulls down when trying to access Curseforge modpacks when I run fjord from a terminal, old key works fine

**Comment by lemonzest79** [comment]
New key downloading code works for me now

**Comment by evan-goode** [comment]
Released https://github.com/unmojang/FjordLauncher/releases/tag/8.4
