### ISSUE TITLE
Failed to fetch Curseforge API Key

### ISSUE THREAD

**Issue by Sorangan** [unmojang/FjordLauncher#16]
### Operating System

Windows

### Version of Fjord Launcher

8.4

### Version of Qt

6.6.3

### Description of bug

![fjБезымянный](https://github.com/unmojang/FjordLauncher/assets/20504086/1a477ab3-d681-4462-b2d9-3e9e3c9f49a2)

### Steps to reproduce

The first time you run the Launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by evan-goode** [comment]
Resolved in Fjord Launcher 8.4.1.
