### ISSUE TITLE
Addings a FTB instance doesn't download modloader (neoforge)

### ISSUE THREAD

**Issue by Panderine** [unmojang/FjordLauncher#17]
### Operating System

Windows

### Version of Fjord Launcher

Fjord Launcher 8.4.1

### Version of Qt

QT 6.6.3

### Description of bug

When adding a FTB instance, the modloader is not installed.

### Steps to reproduce

1. Add instance
2. Select "FTB"
3. Select "FTB NeoTetch

Launcher downloads every mod but not the modloader (Neoforge in this pack)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by evan-goode** [comment]
Thanks, Neoforge should get installed now. Unfortunately, I can't get that modpack working specifically; there is some issue installing versions of Neoforge for 1.20.4. The same bug is present in Prism Launcher, so I'll file an issue there.

**Comment by evan-goode** [comment]
Fixed now, it was some issue with the metadata server.

**Comment by Panderine** [comment]
ty!

**Comment by zippoking** [comment]
Unfortunately this is not fixed for me. I did a clean installation of FjordLauncher with scoop. Then added FTB Neotech. All the mods have been downloaded but the modloader is not present. Is this a mistake on my end or still something you need to fix?

I also tried with the latest FTB Unstable 1.21, which said to be exclusively available for NeoForge. But the mod loader is just not getting installed.

Thank in advance!
PS: can i add Neoforge manually? If so, how do i know which version to use?

**Comment by evan-goode** [comment]
This is still pending release. Try one of the development builds and see whether that works, e.g. https://github.com/unmojang/FjordLauncher/actions/runs/10345138339.

**Comment by zippoking** [comment]
Thanks for the quick response. I have no idea how to use a development build. I don't know where to download the fjordlauncher on your link. I will just wait a little bit longer for an official release :-)

**Comment by evan-goode** [comment]
Just released Fjord Launcher 8.4.2 :)
