### ISSUE TITLE
vulkan mods don't work

### ISSUE THREAD

**Issue by I-like-stuff** [unmojang/FjordLauncher#19]
### Operating System

Linux

### Version of Fjord Launcher

Fjord Launcher 8.4

### Version of Qt

Qt 6.7.2

### Description of bug

if I run a different instance with the vulkanmod installed, I get this 
![image](https://github.com/unmojang/FjordLauncher/assets/109248186/8fa4b6a3-06e6-4156-8d0c-acab89f36b8a)

there was a way to tackle this in prismlauncher and the now dead pollymc which was to add "additional libs" and then insert "vulkan-loader" to fix the problem in Nixos however that doesn't seem to work here in fjord so I'm not sure 

### Steps to reproduce

install vulkanmod on any instance and you'll likely going to run in the same issue 

### Suspected cause

vulkan-loader isn't included as a dependency over in the fjord launcher nix package which is preventing me from adding it as an additional library

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by i-can-not-program** [comment]
> there was a way to tackle this in prismlauncher and the now dead pollymc which was to add "additional libs" and then insert "vulkan-loader" to fix the problem in Nixos however that doesn't seem to work here in fjord so I'm not sure

It works for me with this:
```nix
fjordlauncher.override { additionalLibs = [ vulkan-loader ]; }
```
I don't think this should be added by default, since it is not required by the vanilla game and additional libraries can easily be added.

**Comment by evan-goode** [comment]
The prismlauncher derivation in nixpkgs has vulkan-loader as of https://github.com/NixOS/nixpkgs/pull/303880, but the derivation in Prism's upstream repository (and therefore Fjord's) doesn't. I'm happy to cherry-pick this in for now, and I'll ask upstream about keeping their derivation in sync with nixpkgs.

**Comment by evan-goode** [comment]
I filed https://github.com/PrismLauncher/PrismLauncher/pull/2667, let's wait for that.
