### ISSUE TITLE
Fjord launcher won't launch

### ISSUE THREAD

**Issue by hownioni** [unmojang/FjordLauncher#20]
### Operating System

Linux

### Version of Fjord Launcher

Fjord Launcher 8.4.1-1

### Version of Qt

6.7.2-1

### Description of bug

It doesn't launch, instead it spits out this message on the terminal:
```
warning: direct reference to protected function `_ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex' in `/usr/lib/libQt6Widgets.so.6' may break pointer equality
fjordlauncher: _ZNK19QStyledItemDelegate15initStyleOptionEP20QStyleOptionViewItemRK11QModelIndex: /usr/lib/libQt6Widgets.so.6: error due to GNU_PROPERTY_1_NEEDED_INDIRECT_EXTERN_ACCESS
```

### Steps to reproduce

Launch from the terminal

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hownioni** [comment]
I have to add that I installed fjordlauncher-bin package from AUR

**Comment by evan-goode** [comment]
This looks like https://github.com/PrismLauncher/PrismLauncher/issues/991, it seems like their resolution was to leave `prismlauncher-bin` in the AUR but recommend `prismlauncher` instead (or rather now, the `prismlauncher` in official repos).

I don't have a great solution to this, I think I might just remove the `fjordlauncher-bin` package. Maybe we can get Fjord added to Chaotic AUR so users don't always have to build it themselves?

**Comment by hownioni** [comment]
the qt5-bin version works though, maybe it's something with qt6?

**Comment by evan-goode** [comment]
The README no longer recommends the `fjordlauncher-bin` package, and the README mentions that `fjordlauncher` is in the Chaotic AUR for those Arch users wanting a quick binary install, so I'll close this.
