### ISSUE TITLE
Neoforge loader latest versions not available to download

### ISSUE THREAD

**Issue by Panderine** [unmojang/FjordLauncher#28]
### Version of Fjord Launcher

Fjord launcher 8.4.2

### Version of Qt

QT 6.6.3

### Description of bug

Try to install loader Neoforge any version greater than  21.1.35 and they are not even in the list

### Steps to reproduce

Create custom instance, install loader, choose neoforge try to install version 21.1.37

Also If you install a modpack from curseforge that uses latest version, it fails installation aswell. i.e. ATM10

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Panderine** [comment]
The issue seems to be in the metadata  url:

https://meta.unmojang.org/v1/net.neoforged/ 

`"versions": [
        {
            "recommended": false,
            "releaseTime": "2024-09-01T23:04:22.293738+00:00",
            "requires": [
                {
                    "equals": "1.21.1",
                    "uid": "net.minecraft"
                }
            ],
            "sha256": "f42da7b27631e3256467c2eef645fdcd5fab7d24d227da95fdc7e2b675d9c0e7",
            "version": "21.1.35"`

https://meta.prismlauncher.org/v1/net.neoforged/

`"versions": [
        {
            "recommended": false,
            "releaseTime": "2024-09-03T16:05:14.312984+00:00",
            "requires": [
                {
                    "equals": "1.21.1",
                    "uid": "net.minecraft"
                }
            ],
            "sha256": "9efda47b4cdadc7559932cd832217b21ca44b0f582cf31a43fd94dba896b41d9",
            "version": "21.1.37"`

**Comment by evan-goode** [comment]
Fixed now. Our metadata was 3 days behind since GitHub disabled the update action due to "repository inactivity". I've added this action: https://github.com/liskin/gh-workflow-keepalive, hopefully that will prevent it from happening again.
