### ISSUE TITLE
What are the differences between Fjord and PollyMC?

### ISSUE THREAD

**Issue by TechPro424** [unmojang/FjordLauncher#3]
What are the differences between Fjord and [PollyMC](https://github.com/fn2006/PollyMC)?
From what I've heard, this fork was started because PollyMC has been inactive

But other than keeping up with the latest Prism version, are there any features that Fjord provides and PollyMC does not?

**Comment by evan-goode** [comment]
I wouldn't say there are any new features yet, just bug fixes, see these release notes: https://github.com/unmojang/FjordLauncher/releases/tag/8.3.

In the future, my goals for Fjord Launcher are to:

- Maintain support for alternative auth servers
- Minimize the launcher's dependence on network services (e.g. we probably don't need to fetch Prism's RSS feed all the time). Ideally the game could be launched and only make HTTP requests to the authentication servers, no one else.
- Somehow bundle an MSA client ID so Microsoft authentication works out of the box
- Package it for (almost every) system that Prism Launcher supports
