### ISSUE TITLE
Can't get FTB NeoTech fresh instance to start (neoForge)

### ISSUE THREAD

**Issue by Panderine** [unmojang/FjordLauncher#31]
### Operating System

Windows

### Version of Fjord Launcher

Fjord Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

Instance won't start from fresh install

### Steps to reproduce

Add instance from curseforge. Select FTB Neotech modpack

### Suspected cause

Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
One or more subtasks failed

cant find any more detailed logs about this

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Panderine** [comment]
I think the issue is again with neoforge. Can't get to download the requiered libs even on a fresh instance (no modpack).
EDIT: Issue is with neoforge v20.4.237 (latest) previous version does download the libs and launch. Maybe meta server again?

**Comment by evan-goode** [comment]
I couldn't reproduce this using Minecraft 1.20.4 and NeoForge 20.4.237. Could have been a transient issue with NeoForge's infra. Maybe try clearing your metadata cache (main menu -> Help -> Clear Metadata Cache).

I don't see anything immediately wrong with the metadata server. Ours and prismlauncher's agree that that sha256 of that version of NeoForge is `5a6e0d83f97e85e57d6cdbaa91618bd31f9c0e63f8942ab4f564be8912aa99eb`.

If you are able, could you try reproducing this with Prism Launcher, or using Prism Launcher's metadata server? (main menu -> Settings -> APIs -> Services -> change Metadata Server to `https://meta.prismlauncher.org/v1/`)

**Comment by Panderine** [comment]
It fails with the same error using prism metadata server. 
After clearing cache it also fails. 
If I change version to 20.4.236 it works  :(

It works in other launchers ... will try Prism.

EDIT: It works in Prism

**Comment by Panderine** [comment]
Any way to log or debugg the lib fetching process?

**Comment by evan-goode** [comment]
You could also try with a totally fresh `~/.local/share/FjordLauncher` (and back up the old one).

I debug network stuff by running mitmproxy and configuring Fjord Launcher to use the HTTP proxy server localhost:8080. You'll need to install the mitmproxy certificate: https://docs.mitmproxy.org/stable/concepts-certificates. There could also be some output on stderr or stdout when running Fjord Launcher from the command line.

The two URLs that are different between 20.4.236 and 20.4.237 are:

- https://maven.neoforged.net/net/neoforged/neoforge/20.4.237/neoforge-20.4.237-installer.jar
- https://maven.neoforged.net/releases/net/neoforged/neoforge/20.4.237/neoforge-20.4.237-universal.jar

Are you able to download both of these outside Fjord/Prism?

**Comment by Panderine** [comment]
Yes, I'm able to download both jars from a browser.

If I delete FjordLauncher\libraries\net\neoforged\neoforge\20.4.237 folder, and launch a plain instance again, it dowloads neoforge-20.4.237-universal.jar but the instance doesn't starts. It shows:

"Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
One or more subtasks failed"

**Comment by Panderine** [comment]
Did nothing, tried again today and it worked with neoforge 20.4.237... dunno what happened but was clearly from my side. Sorry and thanks for your time!
