### ISSUE TITLE
Prism 9.0 (and now 9.1) are out!

### ISSUE THREAD

**Issue by LunisCandle** [unmojang/FjordLauncher#36]
### Role

I play modded minecraft and believe others could benefit from this.

### Suggestion

Merge in PrismLauncher 9.0 as it's released with a few major features.

### Benefit

To keep the launcher features in parity with upstream.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by LunisCandle** [comment]
Whoops, 9.1 is out now also!

https://github.com/PrismLauncher/PrismLauncher/releases/tag/9.1

**Comment by evan-goode** [comment]
Resolved: https://github.com/unmojang/FjordLauncher/releases/tag/9.1.0
