### ISSUE TITLE
Change ReadMe to mention being a fork of pollymc

### ISSUE THREAD

**Issue by hl2jeep** [unmojang/FjordLauncher#4]
### Role

Play modded mc

### Suggestion

title

### Benefit

so people know this is the continuation of pollymc rather than a whole new launcher

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by evan-goode** [comment]
Done in https://github.com/unmojang/FjordLauncher/commit/e0b545152a777ea6cf4487eca0b5949b5875181f
