### ISSUE TITLE
Ely.by avatars is not loading.

### ISSUE THREAD

**Issue by Ivanoshechka** [unmojang/FjordLauncher#40]
### Operating System

Windows 11 pro. 22H2

### Version of Fjord Launcher

9.1.0 Release and [9.1.0-develop from actions](https://github.com/unmojang/FjordLauncher/actions/runs/11990579451).

### Version of Qt

6.7.3.

### Description of bug

Ely.by account's are working but avatars is not loading. (Even when adding new account.)

https://github.com/user-attachments/assets/109b99c2-ab6d-4e36-a6b2-45173b49cdfb

### Steps to reproduce

Refresh a Ely.by account. (Or add new.)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by evan-goode** [comment]
I couldn't reproduce this on Fjord Launcher 9.1.0  on Windows 10 Enterprise 22H2, logging in with my Ely.by email address.

Is there any relevant output in the console? On Windows, you can view the console logs by running Fjord Launcher from the command line (Open Windows Terminal and type `C:\path\to\fjordlauncher\fjordlauncher.exe`).

Are you sure the Ely.by account has a skin? Do other launchers, such as HCML, load the skin correctly? Are you logging in with your email address or your player name? Do you see the same bug with other authentication servers? You can try making an account on https://skin.prinzeugen.net/ for example.

**Comment by Ivanoshechka** [comment]
I tried create a account in Blessing Skin and littleskin. But I couldn’t log in from which one:

* Blessing Skin saying: 用户 [IvanokSecond] 不存在 
(*User [IvanokSecond] does not exist*) ((And i didn't get email to verify my account in total.))
* Littleskin saying: Minecraft Java profile response could not be parsed. 
(I have same error with microsoft account too in Fjord.)

**But!**
In cmd i think, i prob see the problem:

> 
    20.590 D | [launcher.task.net.upload]: "{8016105b-438c-4175-82ac-22079bc223dc}" Runninng  "https://account.ely.by/api/authlib-injector"
    20.964 D | [launcher.task.net.upload]: "{8016105b-438c-4175-82ac-22079bc223dc}" Request succeeded: "https://account.ely.by/api/authlib-injector"
    20.964 D | AuthFlow: "Logging in with Yggdrasil."
    20.964 D | [launcher.task.net.upload]: "{e4e9697a-0c29-4b47-8d1a-ccc389579521}" Runninng  "https://account.ely.by/api/authlib-injector/authserver/authenticate"
    21.788 D | [launcher.task.net.upload]: "{e4e9697a-0c29-4b47-8d1a-ccc389579521}" Request succeeded: "https://account.ely.by/api/authlib-injector/authserver/authenticate"
    21.788 D | Yggdrasil request done
    21.788 D | Getting access token.
    21.788 D | AuthFlow: "Fetching the Minecraft profile."
    21.956 D | Parsing Minecraft profile...
    21.957 D | AuthFlow: "Getting skin."
    22.181 C | [launcher.task.net.download]: "{d427c2fe-d6cb-457e-b0fb-535a3fa1de6f}" Failed "http://ely.by/minecraft/skins/5c3d07fe26dd448d63ed463446adac27.png" with reason QNetworkReply::ContentNotFoundError
    22.181 C | [launcher.task.net.download]: "{d427c2fe-d6cb-457e-b0fb-535a3fa1de6f}" HTTP Status 404 ;error "Error transferring http://ely.by/minecraft/skins/5c3d07fe26dd448d63ed463446adac27.png - server replied: Not Found"
    22.466 C | [launcher.task.net.download]: "{d427c2fe-d6cb-457e-b0fb-535a3fa1de6f}" Failed "http://ely.by/minecraft/skins/5c3d07fe26dd448d63ed463446adac27.png" with reason QNetworkReply::ContentNotFoundError
    22.466 C | [launcher.task.net.download]: "{d427c2fe-d6cb-457e-b0fb-535a3fa1de6f}" HTTP Status 404 ;error "Error transferring http://ely.by/minecraft/skins/5c3d07fe26dd448d63ed463446adac27.png - server replied: Not Found"
    22.636 C | [launcher.task.net.download]: "{d427c2fe-d6cb-457e-b0fb-535a3fa1de6f}" Failed "http://ely.by/minecraft/skins/5c3d07fe26dd448d63ed463446adac27.png" with reason QNetworkReply::ContentNotFoundError
    22.636 C | [launcher.task.net.download]: "{d427c2fe-d6cb-457e-b0fb-535a3fa1de6f}" HTTP Status 404 ;error "Error transferring http://ely.by/minecraft/skins/5c3d07fe26dd448d63ed463446adac27.png - server replied: Not Found"
    22.639 D | Inserting account at index 1
    22.639 D | Writing account list to "accounts.json"
    22.640 D | Building JSON data structure.
    22.640 D | Building account array.
    22.640 D | Writing account list to file.
    22.647 D | Saved account list to "accounts.json"
    25.244 D | Writing account list to "accounts.json"
    25.244 D | Building JSON data structure.
    25.244 D | Building account array.
    25.245 D | Writing account list to file.
    25.251 D | Saved account list to "accounts.json"
    26.705 D | Paged dialog close requested
    26.706 D | Sorting icon list...
    26.707 D | Detecting proxy settings...
    26.707 D | Using no proxy is an option!
    26.707 D | Paged dialog close approved
    26.707 D | Paged dialog geometry saved
>  
But the authlib-injector is working anyway?

![image](https://github.com/user-attachments/assets/bd54ce11-ecd5-4f46-80ea-21014a144658)
![image](https://github.com/user-attachments/assets/87205bfe-769b-4a30-94f4-7827fba91ce1)
(1.0 can't load the skin, but i think it's 1.0 skill isusse.)

**Comment by Ivanoshechka** [comment]
I just re-upload skin on ely.by and it's start seeing the skin again. Kek.
