### ISSUE TITLE
There is no fjordlauncher in nixpkgs

### ISSUE THREAD

**Issue by sanngridhr** [unmojang/FjordLauncher#46]
### Operating System

Linux

### Version of Fjord Launcher

any version

### Version of Qt

any version

### Description of bug

There is no fjordlauncher in nixpkgs

### Steps to reproduce

```sh
orest ~ > nix profile install nixpkgs#fjordlauncher
error: flake 'flake:nixpkgs' does not provide attribute 'packages.x86_64-linux.fjordlauncher', 'legacyPackages.x86_64-linux.fjordlauncher' or 'fjordlauncher'
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by blryface** [comment]
how tf is this considered a *bug*

**Comment by Duckly12970** [comment]
@blryface lol

**Comment by sanngridhr** [comment]
https://github.com/unmojang/FjordLauncher/blob/develop/nix/README.md#installing-a-stable-release-nixpkgs

It is a documentation bug.

**Comment by evan-goode** [comment]
So it is, thanks. Fixed, unless I missed something. I would like to add Fjord to nixpkgs but that should be an package request on NixOS/nixpkgs, not an issue here.

**Comment by blryface** [comment]
I've heard from someone involved in nixos that there's no way they're gonna add anything related to piracy

They've also said they don't have anything personally against it but would rather just stay legal and legitimate to avoid legal issue
