### ISSUE TITLE
Possibility of adding back offline accounts

### ISSUE THREAD

**Issue by kiakong** [unmojang/FjordLauncher#9]
### Role

Playing MC

### Suggestion

Make adding MS account optional

### Benefit

Anyone can use the launcher to play MC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I can't even make an excuse for this, i just want to play MC.
I can't buy MC in my country so we mostly use launchers that can run offline accounts. PollyMC was a good/safe alternative for any sketchy launcher (TLauncher, etc.)
Can you please revert the change for needing a MS account?

**Comment by Darthagnon** [comment]
The following commits add DRM to FjordLauncher:
- [Add DRM notice](https://github.com/unmojang/FjordLauncher/commit/67846827f534af123f9c22784e029caa2f5bdc30)
- [Add back DRM for offline and authlib-injector accounts](https://github.com/unmojang/FjordLauncher/commit/13a32a66422e171c59ce861680fd184587057d08)
- [DRM: check for valid account, not just any account](https://github.com/unmojang/FjordLauncher/commit/513361df25485cb2e4593820084e5ee71e6e5a23)

I'm wondering if this was done preemptively to avoid a DMCA takedown. That said, none of the other launchers without DRM have been taken down. 

In my opinion, this change also disqualifies FjordLauncher as a successor to PollyMC and HMCL/Hello Minecraft. At this point, why even bother with Authlib Injector? Might as well just be another fork of MultiMC5 or PolyMC/Prism Launcher

**Comment by TechnoSparks** [comment]
I think it is a matter of principle. From what I could understand, the whole "unmojang" organisation goal is to remove Mojang in the equation when playing Minecraft, primarily API and auth (look at drasl), but that doesn't mean the launcher needs to be DRM-free. For a boiled-down simple analogy, it's like using open source software on an operating system one has paid for (Windows).

It's a free software after all, if someone really want they could make personal patches like what UltimMC/PolyMC did, or analyse the behaviour of the software for possible workarounds (I found DRM could be bypassed easily without the need for patching or customised build for MultiMC, Prism and Fjord)

**Comment by vitalii0133** [comment]
> (I found DRM could be bypassed easily without the need for patching or customised build for MultiMC, Prism and Fjord)
How?

**Comment by catfromplan9** [comment]
> > (I found DRM could be bypassed easily without the need for patching or customised build for MultiMC, Prism and Fjord)
> 
> How?

Make an `accounts.json` file in the launcher's data directory with the following content

```
{
    "accounts": [
        {
            "active": true,
            "profile": {
                "capes": [
                ],
                "id": "0",
                "name": "Steve",
                "skin": {
                    "id": "",
                    "url": "",
                    "variant": ""
                }
            },
            "type": "Offline",
            "ygg": {
                "extra": {
                    "clientToken": "0",
                    "userName": "Steve"
                },
                "iat": 0,
                "token": "offline"
            }
        }
    ],
    "formatVersion": 3
}
```

Open Fjord Launcher, add your account, and now you can remove "Steve"

**Comment by omnigenous** [comment]
@catfromplan9 not sure if it related, but it crashes for me with following errors:
```
java.lang.IllegalStateException: Rendersystem called from wrong thread
java.lang.IllegalArgumentException: Invalid UUID string: <PROFILE ID>
```

**Comment by catfromplan9** [comment]
> @catfromplan9 not sure if it related, but it crashes for me with following errors:
> 
> ```
> java.lang.IllegalStateException: Rendersystem called from wrong thread
> java.lang.IllegalArgumentException: Invalid UUID string: <PROFILE ID>
> ```

Seems unrelated. Don't launch the Steve account though, as I said. Add a new offline account, then remove Steve

**Comment by omnigenous** [comment]
@catfromplan9 I can't read... Deleted "Steve" account and added new offline account. Now it's works and errors are gone too, so it was related. Thank you!

**Comment by FN-FAL113** [comment]
> > > (I found DRM could be bypassed easily without the need for patching or customised build for MultiMC, Prism and Fjord)
> > 
> > 
> > How?
> 
> Make an `accounts.json` file in the launcher's data directory with the following content
> 
> ```
> {
>     "accounts": [
>         {
>             "active": true,
>             "profile": {
>                 "capes": [
>                 ],
>                 "id": "0",
>                 "name": "Steve",
>                 "skin": {
>                     "id": "",
>                     "url": "",
>                     "variant": ""
>                 }
>             },
>             "type": "Offline",
>             "ygg": {
>                 "extra": {
>                     "clientToken": "0",
>                     "userName": "Steve"
>                 },
>                 "iat": 0,
>                 "token": "offline"
>             }
>         }
>     ],
>     "formatVersion": 3
> }
> ```
> 
> Open Fjord Launcher, add your account, and now you can remove "Steve"

created a data folder beside the launcher executable, seems to be not working.

**Comment by hero-persson** [comment]
Hello, I am maintaining a DRM-free version called Fjord Launcher Unlocked: https://github.com/hero-persson/FjordLauncherUnlocked. I haven't made Arch and Gentoo packages yet. But I might. Please check it out (:

**Comment by omnigenous** [comment]
@hero-persson would love to see aur package!

**Comment by hero-persson** [comment]
> @hero-persson would love to see aur package!

I made https://aur.archlinux.org/packages/fjordlauncherunlocked and https://aur.archlinux.org/packages/fjordlauncherunlocked-git. No bin package since it's broken on Prism and Fjord. But maybe Fjord Launcher Unlocked can go in Chaotic AUR too.

**Comment by catfromplan9** [comment]
> Hello, I am maintaining a DRM-free version called Fjord Launcher Unlocked: https://github.com/hero-persson/FjordLauncherUnlocked. I haven't made Arch and Gentoo packages yet. But I might. Please check it out (:

A gentoo package for this would be pointless. You can simply apply a patch file to fjord by placing it in `/etc/portage/patches/games-action/fjordlauncher`, and I have already done so

**Comment by catfromplan9** [comment]
> > > > (I found DRM could be bypassed easily without the need for patching or customised build for MultiMC, Prism and Fjord)
> > > 
> > > 
> > > How?
> > 
> > 
> > Make an `accounts.json` file in the launcher's data directory with the following content
> > ```
> > {
> >     "accounts": [
> >         {
> >             "active": true,
> >             "profile": {
> >                 "capes": [
> >                 ],
> >                 "id": "0",
> >                 "name": "Steve",
> >                 "skin": {
> >                     "id": "",
> >                     "url": "",
> >                     "variant": ""
> >                 }
> >             },
> >             "type": "Offline",
> >             "ygg": {
> >                 "extra": {
> >                     "clientToken": "0",
> >                     "userName": "Steve"
> >                 },
> >                 "iat": 0,
> >                 "token": "offline"
> >             }
> >         }
> >     ],
> >     "formatVersion": 3
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Open Fjord Launcher, add your account, and now you can remove "Steve"
> 
> created a data folder beside the launcher executable, seems to be not working.

That is not where it will be located. The directory I am referring to is the directory where the "instances" folder and such are stored, not a directory actually called "data"

**Comment by evan-goode** [comment]
Sorry, I will not remove the DRM check from Fjord Launcher. Regardless of my personal ethical beliefs on the matter, I am developing this software under my own name, as a signatory of the Minecraft EULA, and I don't want to risk a DMCA takedown or worse.

> I'm wondering if this was done preemptively to avoid a DMCA takedown. That said, none of the other launchers without DRM have been taken down.

[Legacy Launcher](https://llaun.ch/en) was taken down by a DMCA request (according to them).

> In my opinion, this change also disqualifies FjordLauncher as a successor to PollyMC and HMCL/Hello Minecraft.

Correct. It should not be treated as such.

> At this point, why even bother with Authlib Injector? Might as well just be another fork of MultiMC5 or PolyMC/Prism Launcher

There are [many reasons](https://github.com/PrismLauncher/PrismLauncher/pull/543#issue-1474172532) why you might want to use third-party accounts. Not owning a Minecraft license is just one of them. But whether you own the game or not, having Fjord be a "legitimate", EULA-respecting launcher is good because it legitimizes other projects in the custom auth space, such as [Drasl](https://github.com/unmojang/drasl). Developing a system to self-host your own authentication servers is a substantial effort, and it's easier to attract developers and sustain these projects long-term if they are legal and in line with Mojang's rules.

> I think it is a matter of principle. From what I could understand, the whole "unmojang" organisation goal is to remove Mojang in the equation when playing Minecraft, primarily API and auth (look at drasl), but that doesn't mean the launcher needs to be DRM-free.

Yes, generally my goal is to make it easier to play Minecraft with only the bare minimum of proprietary components (i.e. the Minecraft client and the Minecraft server), and for everything else to be libre. But it may be illegal to distribute a launcher that doesn't include this "DRM check" that relies on Microsoft's servers, so we just have to do our best within the lines of the law.

It seems there are already several projects downstream of Fjord Launcher which remove this DRM check. I cannot endorse using any of these, and please refrain from discussing them here.

**Comment by ghost** [comment]
> > > (I found DRM could be bypassed easily without the need for patching or customised build for MultiMC, Prism and Fjord)
> > 
> > 
> > How?
> 
> Make an `accounts.json` file in the launcher's data directory with the following content
> 
> ```
> {
>     "accounts": [
>         {
>             "active": true,
>             "profile": {
>                 "capes": [
>                 ],
>                 "id": "0",
>                 "name": "Steve",
>                 "skin": {
>                     "id": "",
>                     "url": "",
>                     "variant": ""
>                 }
>             },
>             "type": "Offline",
>             "ygg": {
>                 "extra": {
>                     "clientToken": "0",
>                     "userName": "Steve"
>                 },
>                 "iat": 0,
>                 "token": "offline"
>             }
>         }
>     ],
>     "formatVersion": 3
> }
> ```
> 
> Open Fjord Launcher, add your account, and now you can remove "Steve"

It works in Prism Launcher 9.0 Flatpak, but it's a bit cramped: you have to set up it in the settings every time you restart the app.
UPD: I didn't notice any crap in Prism Launcher 8.4 native.

**Comment by sasha2002** [comment]
<img width="745" height="217" alt="Image" src="https://github.com/user-attachments/assets/52903044-6fef-4f9e-a2fc-504932c31d95" />
How the hell to bypass this shit?
I need ONLY OFFLINE server, how i can add an offline account?

**Comment by catfromplan9** [comment]
> <img alt="Image" width="745" height="217" src="https://private-user-images.githubusercontent.com/5417069/472276414-52903044-6fef-4f9e-a2fc-504932c31d95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM5MzE2MzUsIm5iZiI6MTc1MzkzMTMzNSwicGF0aCI6Ii81NDE3MDY5LzQ3MjI3NjQxNC01MjkwMzA0NC02ZmVmLTRmOWUtYTJmYy01MDQ5MzJjMzFkOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MzFUMDMwODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmNmMjdiNDUzYWUzMjEyMzEzNDA0OWFlYjgxMTQ2NDk4MjBjMmI2OWJhYjAyYjg4MzJkMGVmYzc2NTVhOTQ3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1MhLEMBTJlvsjqcOOR5cgMTGdwWQpbLziPFXIMuBHyQ"> How the hell to bypass this shit? I need ONLY OFFLINE server, how i can add an offline account?

don't use foul language, I'm not going to help you.

**Comment by sasha2002** [comment]
@catfromplan9 

![Image](https://github.com/user-attachments/assets/67d922d8-fcd2-44b1-9ae2-fc7ef6b10249)

**Comment by DraconicNEO** [comment]
> Hello, I am maintaining a DRM-free version called Fjord Launcher Unlocked: https://github.com/hero-persson/FjordLauncherUnlocked. I haven't made Arch and Gentoo packages yet. But I might. Please check it out (:

You need to keep your version updated or it'll break with time.

**Comment by sanngridhr** [comment]
<img width="983" height="391" alt="Image" src="https://github.com/user-attachments/assets/9bef1510-ac3b-495b-baef-a7276dbd0c63" />

I added the suggested fix but it still shows the same error, was there an update I missed?

The file itself:
```
─────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
     │ File: /home/orest/.local/share/FjordLauncher/accounts.json
     │ Size: 796 B
─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 │ {
   2 │     "accounts": [
   3 │         {
   4 │             "active": true,
   5 │             "entitlement": {
   6 │                 "canPlayMinecraft": true,
   7 │                 "ownsMinecraft": true
   8 │             },
   9 │             "profile": {
  10 │                 "canUploadSkins": true,
  11 │                 "capes": [
  12 │                 ],
  13 │                 "id": "0",
  14 │                 "name": "Steve",
  15 │                 "skin": {
  16 │                     "id": "",
  17 │                     "url": "",
  18 │                     "variant": ""
  19 │                 }
  20 │             },
  21 │             "type": "Offline",
  22 │             "ygg": {
  23 │                 "extra": {
  24 │                     "clientToken": "0",
  25 │                     "userName": "Steve"
  26 │                 },
  27 │                 "iat": 0,
  28 │                 "token": "0"
  29 │             }
  30 │         }
  31 │     ],
  32 │     "formatVersion": 3
  33 │ }
─────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by catfromplan9** [comment]
> <img alt="Image" width="983" height="391" src="https://private-user-images.githubusercontent.com/63781175/530382296-9bef1510-ac3b-495b-baef-a7276dbd0c63.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY4MDY0ODksIm5iZiI6MTc2NjgwNjE4OSwicGF0aCI6Ii82Mzc4MTE3NS81MzAzODIyOTYtOWJlZjE1MTAtYWMzYi00OTViLWJhZWYtYTcyNzZkYmQwYzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjI3VDAzMjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzRmNjNmMTRhMjFkNGM5NTg2ZWU4NTI5MjNlMGQzYTU0MTYwYWQxM2Y4OGNiOGJlY2RkODRiYTkzYTUwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iVG7l4RzteKZKE1tiQOEZlWszH9_t-QrM7z6gdyvBto">
> 
> I added the suggested fix but it still shows the same error, was there an update I missed?
> 
> The file itself:
> 
> ```
> ─────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
>      │ File: /home/orest/.local/share/FjordLauncher/accounts.json
>      │ Size: 796 B
> ─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────
>    1 │ {
>    2 │     "accounts": [
>    3 │         {
>    4 │             "active": true,
>    5 │             "entitlement": {
>    6 │                 "canPlayMinecraft": true,
>    7 │                 "ownsMinecraft": true
>    8 │             },
>    9 │             "profile": {
>   10 │                 "canUploadSkins": true,
>   11 │                 "capes": [
>   12 │                 ],
>   13 │                 "id": "0",
>   14 │                 "name": "Steve",
>   15 │                 "skin": {
>   16 │                     "id": "",
>   17 │                     "url": "",
>   18 │                     "variant": ""
>   19 │                 }
>   20 │             },
>   21 │             "type": "Offline",
>   22 │             "ygg": {
>   23 │                 "extra": {
>   24 │                     "clientToken": "0",
>   25 │                     "userName": "Steve"
>   26 │                 },
>   27 │                 "iat": 0,
>   28 │                 "token": "0"
>   29 │             }
>   30 │         }
>   31 │     ],
>   32 │     "formatVersion": 3
>   33 │ }
> ─────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────
> ```

Hello,

I'm sure that this no longer works anymore, changes have been made to the account validation system. There may be other ways around it with a different accounts.json file spoofing an MSA account, however as Evan said this should not be discussed here.

**Comment by DraconicNEO** [comment]
> > <img alt="Image" width="983" height="391" src="https://private-user-images.githubusercontent.com/63781175/530382296-9bef1510-ac3b-495b-baef-a7276dbd0c63.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY4MDY0ODksIm5iZiI6MTc2NjgwNjE4OSwicGF0aCI6Ii82Mzc4MTE3NS81MzAzODIyOTYtOWJlZjE1MTAtYWMzYi00OTViLWJhZWYtYTcyNzZkYmQwYzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjI3VDAzMjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzRmNjNmMTRhMjFkNGM5NTg2ZWU4NTI5MjNlMGQzYTU0MTYwYWQxM2Y4OGNiOGJlY2RkODRiYTkzYTUwOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iVG7l4RzteKZKE1tiQOEZlWszH9_t-QrM7z6gdyvBto">
> > I added the suggested fix but it still shows the same error, was there an update I missed?
> > The file itself:
> > ```
> > ─────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────
> >      │ File: /home/orest/.local/share/FjordLauncher/accounts.json
> >      │ Size: 796 B
> > ─────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────
> >    1 │ {
> >    2 │     "accounts": [
> >    3 │         {
> >    4 │             "active": true,
> >    5 │             "entitlement": {
> >    6 │                 "canPlayMinecraft": true,
> >    7 │                 "ownsMinecraft": true
> >    8 │             },
> >    9 │             "profile": {
> >   10 │                 "canUploadSkins": true,
> >   11 │                 "capes": [
> >   12 │                 ],
> >   13 │                 "id": "0",
> >   14 │                 "name": "Steve",
> >   15 │                 "skin": {
> >   16 │                     "id": "",
> >   17 │                     "url": "",
> >   18 │                     "variant": ""
> >   19 │                 }
> >   20 │             },
> >   21 │             "type": "Offline",
> >   22 │             "ygg": {
> >   23 │                 "extra": {
> >   24 │                     "clientToken": "0",
> >   25 │                     "userName": "Steve"
> >   26 │                 },
> >   27 │                 "iat": 0,
> >   28 │                 "token": "0"
> >   29 │             }
> >   30 │         }
> >   31 │     ],
> >   32 │     "formatVersion": 3
> >   33 │ }
> > ─────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────
> > ```
> 
> Hello,
> 
> I'm sure that this no longer works anymore, changes have been made to the account validation system. There may be other ways around it with a different accounts.json file spoofing an MSA account, however as Evan said this should not be discussed here.

Spoofing an MSA account might work, when I copied my config and accounts.json from PrismLauncher it worked and let me load the game on other offline accounts even though the token wasn't valid for that instance.
